// Code generated by plugin_versions_generate.go; DO NOT EDIT.

package plugins

func GetKubernetesVersion() string {
	return "1.13.3"
}

func GetRandomVersion() string {
	return "2.2.1"
}

func GetVsphereVersion() string {
	return "1.24.3"
}

func GetGoogleVersion() string {
	return "3.27.0"
}

func GetIgnitionVersion() string {
	return "2.1.0"
}

func GetVsphereprivateproviderVersion() string {
	return "1.0.0"
}

func GetIronicVersion() string {
	return "0.2.4"
}

func GetOvirtVersion() string {
	return "1.0.0"
}

func GetAzurermVersion() string {
	return "2.48.0"
}

func GetLocalVersion() string {
	return "1.4.0"
}

func GetAzureprivatednsVersion() string {
	return "1.0.0"
}

func GetLibvirtVersion() string {
	return "1.0.0"
}

func GetKubevirtVersion() string {
	return "1.0.0"
}

func GetOpenstackVersion() string {
	return "1.37.0"
}

func GetAwsVersion() string {
	return "3.1.0"
}
